### ISSUE TITLE
code exit status 203/exec

### ISSUE THREAD

**Issue by fh2levelgh** [TomMuc1/Dump1090-MySQL-Alert-Filter#1]
sudo systemctl status radar.service
● radar.service - radar.php
   Loaded: loaded (/etc/systemd/system/radar.service; enabled; vendor preset: en
   Active: activating (auto-restart) (Result: exit-code) since Thu 2017-11-09 00
  Process: 25710 ExecStart=/home/pi/radar.php (code=exited, status=203/EXEC)
 Main PID: 25710 (code=exited, status=203/EXEC)

**Comment by TomMuc1** [comment]
disable system service radar.php -> run script from terminal and look what happens ...

**Comment by fh2levelgh** [comment]
So, embarrassing, I had a locale issue but thank you for your response it made me realize. Things seem to be working now. Thank you!

**Comment by TomMuc1** [comment]
no big deal - fine that it works now for you
